Vagrant.configure("2") do |config|
  config.vm.box = "boxcutter/ubuntu1404-docker"
  config.vm.provision "shell", path: "install.consul.sh", privileged: false

  (1..3).each do |i|
    config.vm.define "consul-server#{i}" do |cs|
      cs.vm.hostname = "consul-server#{i}"
      cs.vm.network "private_network", ip: "172.20.20.3#{i}"
      cs.vm.provision "shell", path: "provision/setup.consul-server.sh", privileged: false
    end
  end

  config.vm.define "lb" do |lb|
    lb.vm.hostname = "lb"
    lb.vm.network "private_network", ip: "172.20.20.11"
  end

  (1..3).each do |i|
    config.vm.define "web#{i}" do |web|
      web.vm.hostname = "web#{i}"
      web.vm.network "private_network", ip: "172.20.20.2#{i}"
    end
  end

end
